project/activity_signup/forms.py
# project/activity_signup/forms.py

from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Email, Optional

activity_choices = [('soccer', 'Soccer'),
                     ('dodgeball', 'Dodgeball'),
                     ('programming', 'Programming')]

#TODO add more form validators as you learn to use them
class AddEmployeeForm(Form):
    first_name = StringField('First Name:', validators=[DataRequired()])
    last_name = StringField('Last Name:', validators=[DataRequired()])
    email_address = StringField('Email Address:', validators=[DataRequired(), Email()])
    #activity = StringField('Activity:', validators=[DataRequired()])
    activity = SelectField('Activity:', choices=activity_choices )
    comments = TextAreaField('Comments:', validators=[Optional()])

project/activity_signup/__init__.py
# IMPORTS
from flask import Flask

# Config
app = Flask(__name__, instance_relative_config=True)
app.config.from_pyfile('flask.cfg')
from . import views

project/activity_signup/views.py
# Imports
from flask import render_template, Blueprint, request, redirect, url_for, flash
from project import db

from project.models import Employee
from .forms import AddEmployeeForm

# Config
activity_blueprint = Blueprint('activity_signup', __name__, template_folder='templates')

# Routes
@activity_blueprint.route('/', methods=['GET', 'POST'])
def add_employee():
    form = AddEmployeeForm(request.form)
    if request.method == 'POST':
         if form.validate_on_submit():
            new_employee = Employee(form.first_name.data,
                                    form.last_name.data,
                                    form.email_address.data,
                                    form.activity.data,
                                    form.comments.data)
            db.session.add(new_employee)
            db.session.commit()
            flash('New Employee, {} {}, added!'.format(new_employee.first_name, new_employee.last_name), 'success')
            return redirect(url_for('activity_signup.list'))
         else:
             flash_errors(form)
             flash('ERROR! Employee was not added.', 'error')

    # If Method == GET
    return render_template('add_employee.html', form=form)


@activity_blueprint.route('/list')
def list():
    all_employees = Employee.query.all()
    return  render_template('employee.html', employees=all_employees)

project/activity_signup/templates/_form_macros.html
{% macro render_field(field) %}
<div class="form-group" >
    <div class="col-12">
        {% if field.errors %}
        <span class="error">
            {% for error in field.errors %}
            {{ error }}
            {% endfor %}
        </span>
        {% endif %}
    </div>
    <label class="col-2 col-form-label">{{ field.label }}</label>
    <div class="col-10"> {{ field(**kwargs)|safe }}</div>
</div>
{% endmacro %}

project/activity_signup/templates/add_employee.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="page-header">
    <h2>Choose Your Activities</h2>
</div>
<div class="col-md-12" >
<form action="{{ url_for('activity_signup.add_employee') }}" method="post">
    {{ form.csrf_token }}
    {{ render_field (form.first_name, placeholder="First Name") }}
    {{ render_field (form.last_name, placeholder="Last Name") }}
    {{ render_field (form.email_address, placeholder="Email Address") }}
    {{ render_field (form.activity, placeholder="Activity") }}
    {{ render_field (form.comments, placeholder="Comments") }}
    <button class="btn btn-block btn-success" type="submit" >Add Employee</button>
</form>
</div>
{% endblock %}

project/activity_signup/templates/employee.html
{% extends "layout.html" %}
{% block content %}

<div class="page-header">
    <h2>Current Employee Activities</h2>
</div>

<div class="row" >
    <div class="col-md-12 ">
        <!-- TODO Construct a list view for this template @ lower screen widths -->
        <table class="table table-striped">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email Address</th>
                <th>Activity</th>
                <th>Comments</th>
            </tr>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name }}</td>
                <td>{{ employee.email_address }}</td>
                <td>{{ employee.activity }}</td>
                <td>{{ employee.comments }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

project/activity_signup/templates/layout.html
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="utf-8" >
        <title>Employee Activity Signup</title>
        <!-- Bootstrap Stuff CDN -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
              crossorigin="anonymous">
        <!-- Primary StyleSheet -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" >
    </head>

    <body>
            <nav class="navbar navbar-default navbar-static-top">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="{% if request.path == '/list' %}active{% endif %}">
                                <a href="/list">Other Employees</a>
                            </li>
                            <li class="{% if request.path == '/' %}active{% endif %}">
                                <a href="/">Sign Up</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
            
            <div class="container" >
            <!-- Flash Messages -->
            {% for error_message in get_flashed_messages(category_filter=["error"]) %}
            <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
            {% endfor %}
            
            {% for success_message in get_flashed_messages(category_filter=["success"]) %}
            <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
            {% endfor %}
            
            {% for info_message in get_flashed_messages(category_filter=["info"]) %}
            <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
            {% endfor %}
            
            {% block content %}
            {% endblock %}
        </div>
        <!-- Load Scripts -->
        <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
                integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
                crossorigin="anonymous">
        </script>
    </body>
</html>